plugins:
  - jekyll-remote-theme
remote_theme: Resistance-Lab/dubois
kramdown:
  parse_block_html: true
defaults:
  - scope:
      path: ""
    values:
      layout: article

navigation:
  - title: Home
    path:
  - title: Source data
    path: source_data
  - title: Cleaned data
    path: cleaned_data
  - title: Analysis
    path: analysis
  - title: Pipelines
    path: pipelines
exclude: ["venv"]

members:
  -
    name: Geeks for Social Change
    url: https://gfsc.studio
    logo: gfsc.svg
  -
    name: Northern Police Monitoring Project
    url: http://npolicemonitor.co.uk
    logo: npmp.svg
  -
    name: Kids of Colour
    url: https://kidsofcolour.com
    logo: koc.svg
  -
    name: The African Pot Project
    url: https://tapproject.co.uk
    logo: tap.svg
  -
    name: Race, Roots & Resistance
    url: https://www.racerootsresist.com
    logo: rrr.svg
  -
    name: Sites of Resistance
    url: https://sitesofresistance.org/
