plugins:
  - jekyll-remote-theme
remote_theme: Resistance-Lab/dubois
kramdown:
  parse_block_html: true
defaults:
  - scope:
      path: ""
    values:
      layout: article

site_name: Resistance Lab Data Portal
site_description: A collection of data and tools exploring UK state violence

theme_primary_colour: "#C1272D"
theme_secondary_colour: "#000000"

contact_email: info@resistancelab.network
contact_twitter: ResLabMcr
contact_instagram: ResLabMcr
contact_github: Resistance_Lab

google_analytics: UA-173520683-2

navigation:
  - title: Home
    path:
  - title: Source data
    path: source_data
  - title: Cleaned data
    path: cleaned_data
  - title: Analysis
    path: analysis
  - title: Pipelines
    path: pipelines
exclude: ["venv"]

members:
  -
    name: Geeks for Social Change
    url: https://gfsc.studio
    logo: gfsc.svg
  -
    name: Northern Police Monitoring Project
    url: http://npolicemonitor.co.uk
    logo: npmp.svg
  -
    name: Kids of Colour
    url: https://kidsofcolour.com
    logo: koc.svg
  -
    name: The African Pot Project
    url: https://tapproject.co.uk
    logo: tap.svg
  -
    name: Race, Roots & Resistance
    url: https://www.racerootsresist.com
    logo: rrr.svg
  -
    name: Sites of Resistance
    url: https://sitesofresistance.org/
