plugins:
  - jekyll-remote-theme
remote_theme: Resistance-Lab/dubois
kramdown:
  parse_block_html: true
defaults:
  - scope:
      path: ""
    values:
      layout: article

navigation:
  - title: Home
    path:
  - title: Source data
    path: source_data
  - title: Cleaned data
    path: cleaned_data
  - title: Analysis
    path: analysis
  - title: Pipelines
    path: pipelines
exclude: ["venv"]
